resolver: lts-14.19

packages: 
  - codeworld-account
  - codeworld-api
  - codeworld-auth
  - codeworld-compiler
  - codeworld-error-sanitizer
  - codeworld-game-api
  - codeworld-game-server
  - codeworld-prediction
  - codeworld-server
  - codeworld-base
  - funblocks-client

allow-newer: false
  
extra-deps:
  - binary-0.8.7.0
  - blank-canvas-0.6.3
  - colour-2.3.4
  - constraints-extras-0.3.0.2
  - dependent-map-0.3
  - dependent-sum-0.6.1
  - ghc-lib-parser-8.10.1.20200523
  - ghcjs-base-stub-0.3.0.2
  - ghcjs-dom-0.9.4.0
  - ghcjs-dom-jsaddle-0.9.4.0
  - haskell-src-exts-1.20.3
  - hpc-0.6.0.3
  - jsaddle-0.9.6.0
  - jsaddle-dom-0.9.3.2
  - kansas-comet-0.4
  - monoidal-containers-0.6
  - network-2.6.3.6
  - ormolu-0.1.2.0
  - patch-0.0.3.1
  - ref-tf-0.4.0.2
  - reflex-0.6.4.1
  - text-1.2.4.0
  - witherable-0.3.1
